USE ROLE SYSADMIN;

CREATE OR REPLACE TRANSIENT DATABASE DBT_PROD_DB
COMMENT = 'Database to store data of production layer';

CREATE WAREHOUSE IF NOT EXISTS WH_DBT_PROD
    WAREHOUSE_TYPE = 'STANDARD'
    WAREHOUSE_SIZE = 'X-SMALL'
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = 'ECONOMY'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse to be used for dbt production environment';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DBT_BUILDER_PROD_ROLE
COMMENT = 'Role to be used for dbt production environment';

CREATE OR REPLACE USER DBT_BUILDER_PROD_USER
    PASSWORD = 'Ram@12345'
    LOGIN_NAME = 'DBT_PROD_USER'
    DISPLAY_NAME = 'DBT_PROD_USER'
    DISABLED = FALSE
    MINS_TO_UNLOCK = 0
    DEFAULT_WAREHOUSE = 'WH_DBT_PROD'
    DEFAULT_NAMESPACE = 'DBT_PROD_DB'
    DEFAULT_ROLE = 'DBT_BUILDER_PROD_ROLE'
    DEFAULT_SECONDARY_ROLES = ()
    TYPE = 'LEGACY_SERVICE'
    COMMENT = 'User to be used for dbt development environment';

GRANT ROLE DBT_BUILDER_PROD_ROLE TO ROLE SYSADMIN;

GRANT ROLE DBT_BUILDER_PROD_ROLE TO USER DBT_BUILDER_PROD_USER;

GRANT USAGE ON WAREHOUSE WH_DBT_PROD TO ROLE DBT_BUILDER_PROD_ROLE;

GRANT USAGE ON DATABASE DBT_PROD_DB TO ROLE DBT_BUILDER_PROD_ROLE;
GRANT CREATE SCHEMA ON DATABASE DBT_PROD_DB TO ROLE DBT_BUILDER_PROD_ROLE;

USE ROLE ACCOUNTADMIN;

-- Rollback Scripts
-- DROP DATABASE IF EXISTS DBT_DEV_DB;
-- DROP WAREHOUSE IF EXISTS WH_DBT_DEV;
-- DROP ROLE IF EXISTS DBT_BUILDER_DEV_ROLE;
-- DROP USER IF EXISTS DBT_BUILDER_DEV_USER;